### ISSUE TITLE
separator does not except Enter/Carriage Return values

### ISSUE THREAD

**Issue by BrandiATMuhkuh** [jifalops/tags-input#1]
I would like to use enter to separate tags, but no `enter` character I have tried so far word. 
I tried: 

- 13
- \n
- \r
- \u000d
- \&#10;

**Comment by jifalops** [comment]
The default behavior is to allow any whitespace character to separate tags, including \n or \r. If you want only enter to break the tags, use "`Enter`". 

The reason is because the [separator comparison](https://github.com/jifalops/tags-input/blob/master/tags-input.html#L216) is made using `event.key` instead of `event.keyCode` due to compatibility issues for some keys.

https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key/Key_Values#Whitespace_keys

**Comment by BrandiATMuhkuh** [comment]
Thank you it worked!
